version: "3.8"

services:
  next-web-app:
    container_name: next-web-app
    build: ./frontend/contact.ify-web-next-pages/
    ports:
      - "3000:3000"

  dotnet-web-api:
    container_name: dotnet-web-api
    build: ./backend/
    ports:
      - 5234:80
      - 7086:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password12#
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ./https:/https:ro

  db:
    container_name: contactify-db
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    user: root
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "password12#"
      ACCEPT_EULA: "Y"
    volumes:
      - ./data:/var/opt/mssql/data
